### ISSUE TITLE
同学你好，我修改clockin.yml-run无法影响打卡中"今日是否在校"

### ISSUE THREAD

**Issue by tongnimiao** [Brokenice0415/HNUClockIn#1]
无论是python main.py --at_home 0、python main.py --at_home 1、python main.py打卡结果都是不在校

**Comment by Brokenice0415** [comment]
如果是当天已经打过卡的话，修改运行参数后的再次运行并不会修改当天的打卡信息。
你可以看一下你修改参数后的workflow的build步骤的具体运行情况，如果提示“今日已打卡”就是上述情况。
如果是的话，你可以尝试修改参数后看看第二天的打卡结果。

**Comment by tongnimiao** [comment]
开始获取验证码...
获取验证码成功
正在登陆...
登陆成功
今日未打卡，开始打卡......第1次尝试
自动打卡成功
-------------------------
结果是没在校

**Comment by Brokenice0415** [comment]
你判断没在校的依据是否是根据公众号上的当日打卡记录。
如果你在学工系统之前申请了离校，那么你的打卡就会切换为在家的模式，在当你回校后，在宿舍宿管处扫了回校码， 你的打卡系统才会切换为在学校的模式。
如果你五一申请了离校，回校之后你是否已经给宿管扫了“健康开学二维码”呢？

**Comment by tongnimiao** [comment]
谢谢~可能学生和老师打卡方式有点区别，我这边在校和在家是可以手动选择的
