### ISSUE TITLE
定位问题怎么解决

### ISSUE THREAD

**Issue by Able408** [Brokenice0415/HNUClockIn#3]

**Comment by Brokenice0415** [comment]
定位结果是通过表单提交，提交的时候指定参数值就行
在校时默认学校地址定位，在家时的定位信息需要在inform.json中的clockin_inform中填写，注意填写正确的定位地址

**Comment by Able408** [comment]
感谢，我是想问一下，那个湖大的打卡页面用浏览器打开之后不是不能定位吗，这个你是怎么用代码解决的呢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月14日(星期一) 晚上7:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Brokenice0415/HNUClockIn] 定位问题怎么解决 (#3)

**Comment by Brokenice0415** [comment]
那个如果你的电脑是触屏的话其实也是可以在浏览器上选择定位的，但那个不重要
无论你怎么选，最后都是以提交表单时提交的参数值为准
所以只要设置表单中对应参数为你想要定位所在的相应的参数即可
