### ISSUE TITLE
IP相关

### ISSUE THREAD

**Issue by heeler-deer** [Brokenice0415/HNUClockIn#4]
额，那个，有一个问题是，我们在github的action上自动运行脚本时湖大服务器查看的host是本机的host还是github的host啊？我不是太懂host这方面的知识，但在本机上执行脚本的话湖大服务器可以看到我们本机的HOST，网上搜了半天没一个讲清github的action的。不知道一直用github的action会不会被封IP（其实我不太懂orz

**Comment by Brokenice0415** [comment]
我理解你说的host就是类似客户端ip或者MAC的标识
在我理解上ip不是固定的，取决于运行时网络资源的虚拟分配
封ip应该不会，总不能一棍子打死，~~只要不出事~~
